{% set name = "lbfgspp" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/yixuan/lbfgspp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 39c4aaebd8b94ccdc98191d51913a31cddd618cc0869d99f07a4b6da83ca6254

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - eigen >=3,<4
  run:
    - eigen >=3,<4

test:
  source_files:
    - examples/
  requires:
    - {{ compiler('cxx') }}
  commands:
    - test -f $PREFIX/include/LBFGS.h  # [unix]
    - test -f $PREFIX/include/LBFGSB.h  # [unix]
    - test -d $PREFIX/include/LBFGSpp  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\LBFGS.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\include\LBFGSB.h exit 1  # [win]
    - set -ex; for i in examples/*.cpp; do $CXX $CXXFLAGS -I$PREFIX/include/eigen3 -o "$i.out" "$i" && "$i.out"; done  # [unix and target_platform == build_platform]


about:
  license: MIT
  license_file: LICENSE.md
  summary: |
    A header-only C++ library for L-BFGS and L-BFGS-B algorithms
  home: https://lbfgspp.statr.me/
  dev_url: https://github.com/yixuan/LBFGSpp

extra:
  recipe-maintainers:
    - awvwgk
